# Generated by Django 4.2.3 on 2023-07-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75)),
                ('apellido', models.CharField(max_length=75)),
                ('edad', models.IntegerField()),
                ('cedula', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('peso', models.IntegerField()),
                ('altura', models.IntegerField()),
            ],
        ),
    ]
