# Generated by Django 4.2.3 on 2023-07-11 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_alter_paciente_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_emergencia', models.IntegerField()),
                ('parentesco', models.CharField(max_length=75)),
                ('direccion', models.CharField(max_length=150)),
                ('telefono', models.IntegerField()),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=150)),
                ('barrio', models.CharField(max_length=150)),
                ('parroquia', models.CharField(max_length=75)),
                ('canton', models.CharField(max_length=75)),
                ('provincia', models.CharField(max_length=75)),
                ('zona_rural', models.CharField(max_length=75)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ocupacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocupacion', models.CharField(max_length=75)),
                ('empresa', models.CharField(max_length=75)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeguroSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_seguro_salud', models.CharField(max_length=75)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=75)),
                ('segundo_nombre', models.CharField(max_length=75)),
                ('primer_apellido', models.CharField(max_length=75)),
                ('segundo_apellido', models.CharField(max_length=75)),
                ('cedula', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('lugar_nacimiento', models.CharField(max_length=75)),
                ('nacionalidad', models.CharField(max_length=75)),
                ('grupo_cultural', models.CharField(max_length=75)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=75)),
                ('estado_civil', models.CharField(max_length=75)),
                ('instruccion', models.CharField(max_length=75)),
                ('referido_de', models.CharField(max_length=75)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('datos_emergencia_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.datosemergencia')),
                ('direccion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.direccion')),
                ('ocupacion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.ocupacion')),
                ('seguro_salud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.segurosalud')),
            ],
        ),
    ]
