# Generated by Django 4.2.3 on 2023-07-11 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_datosemergencia_direccion_ocupacion_segurosalud_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosemergencia',
            name='telefono',
        ),
    ]
