# Generated by Django 4.2.3 on 2023-07-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_remove_datosemergencia_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosemergencia',
            name='nombre',
            field=models.CharField(default='N/A', max_length=75),
        ),
    ]
