# Generated by Django 4.2.3 on 2023-07-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_datosemergencia_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosemergencia',
            name='nombre',
            field=models.CharField(max_length=75),
        ),
    ]
