# Generated by Django 4.2.3 on 2023-07-11 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0007_alter_datosemergencia_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='datos_emergencia_id',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='direccion_id',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='ocupacion_id',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='seguro_salud',
        ),
        migrations.AddField(
            model_name='datosemergencia',
            name='usuario_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pacientes.usuario'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='usuario_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pacientes.usuario'),
        ),
        migrations.AddField(
            model_name='ocupacion',
            name='usuario_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pacientes.usuario'),
        ),
        migrations.AddField(
            model_name='segurosalud',
            name='usuario_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pacientes.usuario'),
        ),
    ]
