# Generated by Django 4.2.3 on 2023-07-11 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0008_remove_usuario_datos_emergencia_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosemergencia',
            name='usuario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.usuario'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='usuario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.usuario'),
        ),
        migrations.AlterField(
            model_name='ocupacion',
            name='usuario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.usuario'),
        ),
        migrations.AlterField(
            model_name='segurosalud',
            name='usuario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.usuario'),
        ),
    ]
