# Generated by Django 4.2.3 on 2023-07-11 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0009_alter_datosemergencia_usuario_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datosemergencia',
            old_name='usuario_id',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='direccion',
            old_name='usuario_id',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='ocupacion',
            old_name='usuario_id',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='segurosalud',
            old_name='usuario_id',
            new_name='usuario',
        ),
    ]
